-- =============================================================================
-- Supabase Schema: Starter Club Forms
-- Generated by AI Agent | Best Practices Edition
-- =============================================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 1. ENUM TYPES
-- Replace boolean flags with meaningful status states
-- =============================================================================

-- Status for Waitlist Submissions
CREATE TYPE waitlist_status AS ENUM ('pending', 'approved', 'waitlisted', 'contacted', 'archived');

-- Status for Partner Inquiries
CREATE TYPE inquiry_status AS ENUM ('new', 'viewed', 'contacted', 'converted', 'rejected');

-- Source of the submission (e.g., specific form variant)
CREATE TYPE submission_source AS ENUM ('main_form', 'modal_popup', 'other');

-- =============================================================================
-- 2. UTILITY FUNCTIONS
-- =============================================================================

-- Function to automatically update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =============================================================================
-- 3. TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: waitlist_submissions
-- Consolidates data from WaitlistForm.tsx and WaitlistModal.tsx
-- -----------------------------------------------------------------------------
CREATE TABLE waitlist_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Contact Info
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT, -- Captured in Modal
    
    -- Context
    project_idea TEXT, -- Captured in Main Form ('identity')
    
    -- Metadata
    source submission_source DEFAULT 'other',
    status waitlist_status NOT NULL DEFAULT 'pending',
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    -- Constraints
    CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- Index for faster filtering by status and email lookups
CREATE INDEX idx_waitlist_status ON waitlist_submissions(status);
CREATE INDEX idx_waitlist_email ON waitlist_submissions(email);

-- Trigger for updated_at
CREATE TRIGGER update_waitlist_modtime
    BEFORE UPDATE ON waitlist_submissions
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();


-- -----------------------------------------------------------------------------
-- Table: partner_inquiries
-- Handles data from PartnerInquiryForm.tsx
-- -----------------------------------------------------------------------------
CREATE TABLE partner_inquiries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Partner Details
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    organization TEXT NOT NULL,
    
    -- Message
    message TEXT NOT NULL,
    
    -- Metadata
    status inquiry_status NOT NULL DEFAULT 'new',
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    -- Constraints
    CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- Index for status filtering
CREATE INDEX idx_partner_status ON partner_inquiries(status);

-- Trigger for updated_at
CREATE TRIGGER update_partner_modtime
    BEFORE UPDATE ON partner_inquiries
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();


-- =============================================================================
-- 4. ROW LEVEL SECURITY (RLS)
-- Secure tables by default.
-- =============================================================================

-- Enable RLS
ALTER TABLE waitlist_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE partner_inquiries ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- Policies for: waitlist_submissions
-- -----------------------------------------------------------------------------

-- 1. Public Insert: Allow anyone (anon) to sign up
CREATE POLICY "Public can join waitlist"
ON waitlist_submissions FOR INSERT
TO anon
WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- Policies for: partner_inquiries
-- -----------------------------------------------------------------------------

-- 1. Public Insert: Allow anyone to submit inquiry
CREATE POLICY "Public can submit inquiry"
ON partner_inquiries FOR INSERT
TO anon
WITH CHECK (true);
